### ISSUE TITLE
پر نشدن فیلد

### ISSUE THREAD

**Issue by Nazarii76** [Mds92/MD.PersianDateTime#14]
سلام روزتون بخیر
من توی asp net core  
استفاده کردم
اما یک مشکلی هست

وقتی سمت ویو مقدار تاریخ ارسال میشه به سرور 
مقدار 1/1/1
دریافت میشه به مدلی که از جنس کلاس شما ساختم و تاریخ درست دریافت نمیکنه

**Comment by Mds92** [comment]
سلام
دقت کنید برای ارسال پارامتر به بک اند بهترین روش ارسال همون DateTime 
میلادی هست، وقتی به بک اند اطلاعات رسید حالا تبدیلش کنید به 
PersianDateTime
و استفاده کنید
