### ISSUE TITLE
تاریخ امروز یعنی 12 بهمن رو 11 بهمن نمایش می دهد

### ISSUE THREAD

**Issue by adelhoss** [Mds92/MD.PersianDateTime#15]
با سلام
و عرض خسته نباشید خدمت شما بزرگوار عزیز
کتابخانه ی شما امروز یعنی
12 بهمن 1398
رو 11 بهمن 1398
نمایش می دهد
این کدی که استفاده شده :
`            var Persiand = new PersianDateTime(DateTime.Now.Date);
            barStaticItem4.Caption = Persiand.Date.ToString("dddd MM MMMM yyyy");`
خروجی رو هم ببینید خدمت شما 
[نمایش خروجی تاریخ اشتباه](http://www.mediafire.com/convkey/538b/sbprvvl4mdvfvdpzg.jpg?size_id=3)
تا چند روز پیش همه چیز درست کار می کرد اما امروز متاسفانه به مشکل خوردیم
ممنون میشم راهنمایی کنید

**Comment by Mds92** [comment]
سلام
از toString استفاده کنید میبینید که درست هست
مشکل از فرمت شما هست
باید به این شکل تصحیح شود
dddd dd MMMM yyyy
شما به جای dd
از MM استفاده کردید
خوب عدد دورقمی ماه را نشان می دهد

**Comment by adelhoss** [comment]
با سلام کاملا حق با شما است
ممنونیم و مشکل حل شد
باز هم ممنونیم از لطف و راهنمایی شما
کتابخونه ایی که نوشتین بهترین کتابخانه جهت کار با تقویم شمسی است خیلی کامله افرین به شما
خدا قوت
