### ISSUE TITLE
.NET Standard 2.1

### ISSUE THREAD

**Issue by armin-gitter** [Mds92/MD.PersianDateTime#17]
Hello, Can we use this package on .NET Standard 2.1 ?
because in dependencies, version of .NET Standard is 2.0.

**Comment by Mds92** [comment]
Hello,
Sure. No problem

**Comment by Mds92** [comment]
Hello,
Not yet, I'll update it to  .NET Standard 2.1 as soon as possible

**Comment by Mds92** [comment]
Hello,
Sure, No problem
https://dotnet.microsoft.com/platform/dotnet-standard
