### ISSUE TITLE
	PublicKeyToken=null' does not have a strong name !!

### ISSUE THREAD

**Issue by tickerman** [Mds92/MD.PersianDateTime#19]
Severity Code Description Project File Line Suppression State Warning CS8002 Referenced assembly 'MD.PersianDateTime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Dear Mohammad, hi
recently I'm getting this warning when I want to Build the application

please help if you have a solution

**Comment by Mds92** [comment]
Is your assembly signed?
You can use unsigned assemblies if your assembly is also unsigned.
More info:
https://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error
