### ISSUE TITLE
تبدیل تاریخ شمسی به میلادی و بالعکس 

### ISSUE THREAD

**Issue by ambabaei** [Mds92/MD.PersianDateTime#20]
با سلام . آیا با استفاده از این کتابخونه امکان تبدیل تاریخ شمسی ( از نوع رشته ) به میلادی یا تبدیل تاریخ شمسی (از نوع رشته) به میلادی (از نوع DateTime ) وجود داره ؟
با تشکر

**Comment by Mds92** [comment]
سلام
بله
لطفا فایل نخست پروژه یا همون 
readme
را مطالعه کنید
همه چی توش نوشته شده

**Comment by ambabaei** [comment]
ممنون از لطف شما و پاسخ سریعتون . متاسفانه در فایل من هیچ متدی جهت تبدیل به تاریخ شمسی یا میلادی ندیدم . البته شاید از سطح دانش کم بنده باشه . هر چند ممکنه سخت باشه اما اگر راهنمائی بفرمائید که متد تبدیل کدوم هست خیلی خیلی ممنون میشم

**Comment by Mds92** [comment]
```C#
var persianDateTime1 = PersianDateTime.Parse("دوشنبه 05 مرداد 1395 ساعت 04:03");
DateTime dateTime1 = persianDateTime1;
```

**Comment by ambabaei** [comment]
سپاسگذارم
