### ISSUE TITLE
لطفا اگر ممکنه مقدار PersianNumber رو استاتیک بفرمایید

### ISSUE THREAD

**Issue by mbtolou** [Mds92/MD.PersianDateTime#22]
لطفا اگر ممکنه مقدار PersianNumber رو استاتیک بفرمایید

در تعداد زیاد فراخوانی باعث کاهش سرع میشود ، مدل فعلی

**Comment by mbtolou** [comment]
PersianDateTime.Today
PersianDateTime.Now

اینا هم به مشکل میخورن
یعنی نمیشه کاری کرد که اینا هم اعداد انگلیسی تولید کنند

**Comment by Mds92** [comment]
> PersianDateTime.Today
> PersianDateTime.Now
> 
> اینا هم به مشکل میخورن
> یعنی نمیشه کاری کرد که اینا هم اعداد انگلیسی تولید کنند

به صورت پیش فرض 
persianDateTime.PersianNumber
برابر با false
است و کتابخانه به صورت پیش فرض اعداد انگلیسی تولید میکند
