### ISSUE TITLE
تبدیل تاریخ میلادی به شمسی و برعکس

### ISSUE THREAD

**Issue by bensaeed** [Mds92/MD.PersianDateTime#28]
سلام دوست عزيز
بابت اين كار خيلي زحمت كشيديد و كلي متدهاي سودمند و كاربردي توي اون وجود داره .
ولي انصافا فايل راهنماي شما واقعا استفاده كننده رو سردرگم ميكنه.
واسه "تبدیل تاریخ میلادی به شمسی و برعکس " بايد با كلي سعي و خطا پيش رفت كه بشه پبداش كرد آخرش هم پيدا نميشه.
لطفا يه فايل راهنماي ساده بذاريد يكي بتونه راحت ازش استفاده كنه.
من موندم كه براي "تبدیل تاریخ میلادی به شمسی و برعکس" چكار كنم !!!!!!!!؟؟
ممنونم

**Comment by bensaeed** [comment]
من تاريخ رو به ميلادي توي ديتابيس ذخيره ميكنم
و به فارسي ميخوام نمايش بدم
MVC - C#

**Comment by Mds92** [comment]
سلام
```CSharp
var persianDateTime = new PersianDateTime(DateTime.Now);
Console.WriteLine(persianDateTime .ToString()); // نمایش تاریخ شمسی
Console.WriteLine(persianDateTime .ToDateTime().ToString()); // نمایش تاریخ میلادی
```

**Comment by bensaeed** [comment]
مهندس جواب نگرفتم
اصلا همچين  متدي ToDateTime وجود نداره كه بخواد شمسي رو به ميلادي تبديل كنه.
لطفا دقيق راهنمايي بفرمائيد.
