### ISSUE TITLE
Suggestion: adding IFormattable interface

### ISSUE THREAD

**Issue by mahyarff** [Mds92/MD.PersianDateTime#4]
hi
can IFormattable interface be added to PersianDateTime struct as it already includes ToString(string) method?
it can be useful when using DisplayFormat attribute on PersianDateTime property in mvc

**Comment by Mds92** [comment]
Is it work with .Net 2.0, If so, please add it.
Thanks for your notice

**Comment by mahyarff** [comment]
as Microsoft document says, yes, it does
[https://msdn.microsoft.com/en-us/library/system.iformattable(v=vs.80).aspx](url)

**Comment by Mds92** [comment]
I will add it in next version
