### ISSUE TITLE
Add support for DateTimeOffset

### ISSUE THREAD

**Issue by momvart** [Mds92/MD.PersianDateTime#5]
It is suggested to use DateTimeOffset instead of DateTime, and many components now are compatible with it.
Hope to see this in your great library ;)

**Comment by Mds92** [comment]
Thanks for your suggest
Please post a link to see that better

**Comment by momvart** [comment]
[https://blogs.msdn.microsoft.com/davidrickard/2012/04/06/datetime-and-datetimeoffset-in-net-good-practices-and-common-pitfalls/](https://blogs.msdn.microsoft.com/davidrickard/2012/04/06/datetime-and-datetimeoffset-in-net-good-practices-and-common-pitfalls/)
