### ISSUE TITLE
سوال درمورد استفاده تاریخ

### ISSUE THREAD

**Issue by majnouni** [Mds92/MD.PersianDateTime#6]
سلام روز بخیر ، تابع های استفاده شده خیلی خوب بود و فقط یه سوال که 
مثلا چه جوری میشه یه تاریخ به تابع بدیم و روز هفته رو بهمون برگردونه 
ممنون

**Comment by Mds92** [comment]
سلام
این تابع مورد نیاز شما مربوط به دیت پیکر نیست
مربوط میشه به تقویم فارسی که باید از آبجکت دیت جاوا اسکریپت استفاده کنید

**Comment by majnouni** [comment]
یعنی فایل کتابخانه ای شما این امکان رو نمیده ؟

الان نمونه کد را لینکی دارید که من چک کنم
ممنونم

**Comment by Mds92** [comment]
ببخشید من به اشتباه پاسخ دادم
پاسخ صحیح
```
var persianDateTime = new PersianDateTime(1396, 12, 06);
var dayOfWeek = persianDateTime.DayOfWeek;
```
