### ISSUE TITLE
Net Standard

### ISSUE THREAD

**Issue by royapardaz** [Mds92/MD.PersianDateTime#8]
لطفا اگر ممکنه یک نسخه با 2.0 NetStandard روی Nuget قرار بدین.

**Comment by Mds92** [comment]
سلام
برای
.net core 
میتونید پکیج زیر رو نصب کنید
https://www.nuget.org/packages/MD.PersianDateTime.Core/

**Comment by royapardaz** [comment]
روی net core نصب میشه ولی روی net standard خیر

**Comment by Mds92** [comment]
Please see Readme
`Install-Package MD.PersianDateTime.Standard`
