### ISSUE TITLE
ToLongDateTimeInt

### ISSUE THREAD

**Issue by royapardaz** [Mds92/MD.PersianDateTime#9]
<div dir="rtl">
اگر ممکن هست متودی برای تبدیل تاریخ و زمان به مقدار long قرار بدین برای ذخیره در دیتابیس احتیاج دارم.
</div>
<br />
PersianDateTime.Now.ToLongDateTimeString();               // چهارشنبه، ۲۳ اسفند ۱۳۹۶ ساعت ۱۰:۳۲:۴۶
<br />
<br />
long dt = PersianDateTime.Now.<b>ToLongDateTimeInt()</b>;      // 13961223103246
<br />
PersinaDateTime.<b>Parse(dt)</b>.ToLongDateTimeString();        // چهارشنبه، ۲۳ اسفند ۱۳۹۶ ساعت ۱۰:۳۲:۴۶

**Comment by Mds92** [comment]
الان برای تاریخ داریم
یعنی با متد 
ToShortDateInt
میتونید تاریخ رو تبدیل به عدد کنید 
اما این مورد دوم رو ایشالا انجام میدم

**Comment by royapardaz** [comment]
<div dir="rtl">
بله من هم از همون متود برای ذخیره در دیتابیس استفاده میکردم. برای زمان هم از یک TimeSpan استفاده میکردم. امروز اتفاقی جایی این مودل رو مشاهده کردم و گفتم چه بهتر بود که مستقیم هر دو در یک فیلد جدول باشند تا باهم Sort بشن.

**Comment by Mds92** [comment]
تو ورژن جدید اضافه میکنم
ممنون از پیشنهاد شما

**Comment by Mds92** [comment]
ورژن جدید رو بگیرید
